<a href="https://colab.research.google.com/github/JayMoya/FlyHighData_NEW/blob/main/AIDA2_FLYHIGHDATA_LABORATORY_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topic 02: Review of Linear Algebra
$_{\text{©D.J. Lopez | 2021 | Fudamentals of Machine Learning}}$

Linear algebra is undoubtfully one of the foundations of Machine Learning. Through linear algebra, we can perform more optimized techniques in computing an array of numbers wherein mostly used in Machine Learning. In this chapter, we are going to review the concepts, theories, and operations in Linear Algebra that are useful in Machine Learning. For this notebook we will be covering the following topics:
* Vector and Matrix Representation
* Linear Transformation and Matrix Operations
* Vectorization

### Types of Matrices

In [ ]:
import numpy as np
E = np.zeros([4, 4])
D = np.ones([5, 5])
H = np.identity(3)
A = np.array([[3, 9, 6],[3, 2, 7],[3, 2, 1]])
R = np.array([[5, 8, 4], [2, 1, 5], [6, 4, 7]])


def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False
        print(
            f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize: \t{matrix.size}\nRank:\t{matrix.ndim}\nIs Square: {is_square}')
        
        Sum = sum(matrix)
        sums = sum(Sum)
        diag = np.diagonal(matrix)
        result = 1
        for x in diag:
            result = result * x
        if sums == 0:
            print("Zero:", True)
            print("Ones:", False)
            print('Identity:', False)
        elif sums == matrix.size:
            print("Zero:", False)
            print("Ones:", True)
            print('Identity:', False)
        elif result == 1:
            print("Zero:", False)
            print("Ones:", False)
            print('Identity:',True)
        else:
            print("Zero:", False)
            print("Ones:", False)
            print('Identity:', False)
    else:
        print('Matrix is Null')

describe_mat(E)
print("~" * 60)
describe_mat(D)
print("~" * 60)
describe_mat(H)
print("~" * 60)
describe_mat(A)
print("~" * 60)
describe_mat(R)
print("~" * 60)

Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Shape:	(4, 4)
Size: 	16
Rank:	2
Is Square: True
Zero: True
Ones: False
Identity: False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Matrix:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Shape:	(5, 5)
Size: 	25
Rank:	2
Is Square: True
Zero: False
Ones: True
Identity: False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Shape:	(3, 3)
Size: 	9
Rank:	2
Is Square: True
Zero: False
Ones: False
Identity: True
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Matrix:
[[3 9 6]
 [3 2 7]
 [3 2 1]]

Shape:	(3, 3)
Size: 	9
Rank:	2
Is Square: True
Zero: False
Ones: False
Identity: False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Matrix:
[[5 8 4]
 [2 1 5]
 [6 4 7]]

Shape:	(3, 3)
Size: 	9
Rank:	2
Is Square: True
Zero: False
Ones: False
Identity: False
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Arithmetic in Matrices

In [ ]:
import numpy as np


V1 = np.array([[1, 7, 9], [1, 3, 1], [5, 1, 6]])
V2 = np.array([[2, 6, 9], [9, 3, 5], [8, 3, 6]])
V3 = np.array([[6, 6, 6], [9, 4, 5], [5, 6, 2]])
V4 = np.identity(3)
V5 = np.zeros([3,3])



print("Shape of V1: ", V1.shape, "Shape of V2: ", V2.shape,"Shape of V3: ",
      V3.shape,"Shape of V4: ", V4.shape,"Shape of V5: ", V5.shape,)



def Commutative_Property(M1, M2):
    V1V2 = np.dot(M1, M2)
    V2V1 = np.dot(M2, M1)
    print("Commutative Property" '\n')
    print("V1V2" '\n', V1V2)
    print("V2V1" '\n', V2V1)
    print("~" *64)

def Associative_Property(M1, M2, M3):
    V2V3 = np.dot(M2, M3)
    V2V3V1 = np.dot(M1, V2V3)
    V1V2 = np.dot(M1, M2)
    V1V2V3 = np.dot(V1V2, M3)
    print("Associative Property" '\n')
    print("V1V2V3" '\n', V1V2V3)
    print("V2V3V1" '\n', V2V3V1)
    print("~" *64)


def Distributive_Property(M1, M2, M3):
    V2V3 = np.add(M2, M3)
    V1V2V3 = np.dot(M1, V2V3)
    V1V2 = np.dot(M1, M2)
    V1V3 = np.dot(M1, M3)
    print("Distributive Property" '\n')
    print("V1V2V3")
    print(V1V2V3, '\n   =\n', V1V2 + V1V3)

    V2V3V1 = np.dot(V2, M1)
    V2V1 = np.dot(M2, M1)
    V3V1 = np.dot(M3, M1)
    print("V2V3V1")
    print(V2V3V1, '\n    =\n', V2V1 + V3V1)
    print("~" *64)


def Multiplicative_Identity_Property(M1, MIP):
    print("Multiplicative Identity Property" '\n')
    Identity = np.dot(M1, MIP)
    print(Identity, '\n   =\n', M1)
    print("~" *64)


def Multiplicative_Property_of_zero(M1, Zero):
    print("Multiplicative Property of Zero" '\n')
    Z = np.dot(M1, Zero)
    print(Z, '\n   =\n', Zero)
    print("~" *64)


def Dimension_Property(M1, M2):
  A = M1.shape[0]
  B = M2.shape[1]
  print(A, B)

Commutative_Property(V1, V2)
Associative_Property(V1, V2, V3)
Distributive_Property(V1, V2, V3)
Multiplicative_Identity_Property(V1, V4)
Multiplicative_Property_of_zero(V1, V5)
Dimension_Property(V1,V5)

Shape of V1:  (3, 3) Shape of V2:  (3, 3) Shape of V3:  (3, 3) Shape of V4:  (3, 3) Shape of V5:  (3, 3)
Commutative Property

V1V2
 [[137  54  98]
 [ 37  18  30]
 [ 67  51  86]]
V2V1
 [[ 53  41  78]
 [ 37  77 114]
 [ 41  71 111]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Associative Property

V1V2V3
 [[1798 1626 1288]
 [ 534  474  372]
 [1291 1122  829]]
V2V3V1
 [[1798 1626 1288]
 [ 534  474  372]
 [1291 1122  829]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Distributive Property

V1V2V3
[[251 142 157]
 [ 75  42  53]
 [136 121 133]] 
   =
 [[251 142 157]
 [ 75  42  53]
 [136 121 133]]
V2V3V1
[[ 53  41  78]
 [ 37  77 114]
 [ 41  71 111]] 
    =
 [[ 95 107 174]
 [ 75 157 229]
 [ 62 126 174]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Multiplicative Identity Property

[[1. 7. 9.]
 [1. 3. 1.]
 [5. 1. 6.]] 
   =
 [[1 7 9]
 [1 3 1]
 [5 1 6]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Multiplicative Prop

### Transposition

In [42]:
#METHOD 1 used for transposing

import numpy as np
import tensorflow as tf #importing tensorflow libarary/package

matrix_trans = tf.constant([[1,2,3], [4,5,6]], dtype=tf.float32) #Using tensorflow  for transposing
print("Transposed Matrix: \n{}\n".format(matrix_trans))




Transposed Matrix: 
[[1. 2. 3.]
 [4. 5. 6.]]



In [43]:
#METHOD 2 used for transposing
arr1 = [[1,2,3],[4,5,6],[7,8,9]] #Using Nested List Comprehension for transposing 
for row in arr1 :
    print(row)
rez = [[arr1[j][i] for j in range(len(arr1))] for i in range(len(arr1[0]))]
print("\n")
for row in rez:
    print(row)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


### Determinants

### Singular Matrices/Vectors

In [58]:
### Rank 0 matrices

import numpy as np

rank_0 = np.array([[0, 0, 0]])

print("R-0")
for row in rank_0:
    print(row)

rank_matrix= np.linalg.matrix_rank(rank_0) #calculates the Matrix rank of a given matrix using the SVD method
print("Rank of the given Matrix is : ",rank_matrix) #Get the rank of the matrix


R-0
[0 0 0]
Rank of the given Matrix is :  0


In [55]:
### Rank 1 Matrices

import numpy as np

rank_1 = np.array ([[1,0,0],[1,0,0]])
print("Matrix R-1")
for row in rank_1:
    print(row)

rank_matrix = np.linalg.matrix_rank(rank_1) #calculates the Matrix rank of a given matrix using the SVD method
print("Rank of the given Matrix is : ",rank_matrix) #Get the rank of the matrix

Matrix R-1
[1 0 0]
[1 0 0]
Rank of the given Matrix is :  1


In [56]:
### Rank 2 Matrices

import numpy as np

rank_2 = np.array([[1, 2, 1], [3, 4, 7], [3, 6, 3]])
print("Matrix R-2")
for row in rank_2:
    print(row)

rank_matrix= np.linalg.matrix_rank(rank_2) #calculates the Matrix rank of a given matrix using the SVD method
print("Rank of the given Matrix is : ",rank_matrix) #Get the rank of the matrix



Matrix R-2
[1 2 1]
[3 4 7]
[3 6 3]
Rank of the given Matrix is :  2


In [76]:
### Rank N and N-1 Matrices

#RANK N 
a = np.matrix('1 2; 3 4') #If A is of order n×n and |A| ≠ 0, then the rank of A = n.
a

#RANK N-1

matrix([[1, 2],
        [3, 4]])

### Symmetric Vectors

In [64]:
import numpy as np

arr1 = np.array([[ 2, 4, 5 ],
              [ 4, 2, 7 ],
              [ 5, 7, 2 ]])

arr1_trans = arr1.transpose() #Transpose of given array

print(arr1)
print("\n")

if arr1.shape == arr1_trans.shape: # To check if both 'arr1' and the transposed 'arr1' arrays are equal in size

    # comparing the arrays using == and all() method
    if (arr1 == arr1_trans).all():
        print("The Array is Symmetric")
    else:
        print("The Array is Not Symmetric")
else:
    print("The Array is Not Symmetric")

[[2 4 5]
 [4 2 7]
 [5 7 2]]


The Array is Symmetric


### Invertible Matrices

In [73]:
import numpy as np
  
arr1 = np.array([[2, 4, 3],
              [2, -2, 5],
              [3, -9, 4]])
  

print(np.linalg.inv(arr1)) ## Calculating the inverse of the matrix

[[ 0.56060606 -0.65151515  0.39393939]
 [ 0.10606061 -0.01515152 -0.06060606]
 [-0.18181818  0.45454545 -0.18181818]]
